spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/artbots
spring.datasource.username=swunk
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-zcwjkuoda50t70df.us.auth0.com/
